
[ClassVersion("1.0.0.0"), FriendlyName("xDhcpServerBinding")]
class MSFT_DhcpServerBinding : OMI_BaseResource
{
    [Required, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Key] String InterfaceAlias;
};

